title:            "Harshita Chandra"
url:              https://thelastjedi.github.io
permalink:        pretty
highlighter:      pygments
google_analytics: UA-52347455-4
timezone:         Asia/Kolkata
sass:
  sass_dir: assets
  style: :compressed