title:            "Harshita Chandra"
url:              http://harshi.co
permalink:        pretty
highlighter:      pygments
google_analytics: UA-52347455-4
timezone:         Asia/Kolkata
sass:
  sass_dir: assets
  style: :compressed
